version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}carsapi
    build:
      context: .
      dockerfile: Cars.API/Dockerfile

  client:
    image: client
    build:
       context: ../cars-client
       dockerfile: Dockerfile

  proxy:
    image: nginx:mainline

  elk:
    image: sebp/elk